osx_image: xcode8.3
language: objective-c
cache:
  directories:
    - Carthage/
before_install:
  - brew install swiftlint
  - travis_wait 60 script/install
before_script:
  - set -o pipefail
script:
  - xcodebuild -project SlideStock.xcodeproj -scheme SlideStock build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
  - swiftlint
