osx_image: xcode8.3
language: objective-c
before_install:
  - gem install xcpretty
  - brew install swiftlint
  - carthage update --platform iOS --no-use-binaries
before_script:
  - set -o pipefail
script:
  - xcodebuild -project SlideStock.xcodeproj -scheme SlideStock build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
  - swiftlint
