osx_image: xcode8.3
language: objective-c
before_install:
  - gem install xcpretty
  - carthage update --platform iOS --no-use-binaries
before_script:
  - set -o pipefail
script:
  - xcodebuild -project SlideStock.xcodeproj -scheme SlideStock -destination 'platform=iOS Simulator,name=iPhone 6s' -sdk iphonesimulator test | xcpretty -c
